mat-fhir-services/src/main/resources/application-tomcat-local.yaml
Merging to correct problem in MATDEV deployment
=> MAT-351 -fixed bad links in tomcat config part 2

mat-fhir-services/src/main/resources/application-tomcat-local.yaml
=> MAT-351 -fixed bad links in tomcat config part 3

.docker-env.sh
This will remove the sensitive password from the master branch
=> Removing sensitive data

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/OpenApiConfig.java
simply swagger url
https://jira.cms.gov/browse/MAT-810
=> MAT-810 simply swagger url

.gitignore, README.md, cql-elm-translation/src/main/java/gov/cms/mat/cql_elm_translation/controllers/CqlConversionController.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/QdmCqlToFhirCqlConverter.java
- Added git secrets setup to README.md
- Added temp dir to .gitignore
- Fixed default lib versions
- Fixed null annotation node null pointer exception.
=> Latest conversion bug fixes.

scripts/updateHapiGlobalCommonLibs.sh
MAT-177 Changed FHIR_SERVICES_URL to point to localhost by default in the updateHapiGlobalCommonLibs script.
=> MAT-177 Changed FHIR_SERVICES_URL to point to localhost by default in the updateHapiGlobalCommonLibs script.

docker-compose.yml, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/CodeSystemValidator.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/CqlValidatorHelper.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/ValueSetValidator.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/ValueSetVsacAsync.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/VsacValueSetValidator.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlToMatXml.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlUtils.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/rest/MatXmlController.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/ValidationOrchestrationService.java, scripts/updateHapiGlobalCommonLibs.sh
- Fixed existing valueset check.
- Fixed preserving valueset vsac state
- Fixed error messages.
=> MAT-1071 Fixed codesystem/valueset error message and other misc things.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/orchestration/OrchestrationService.java, scripts/updateHapiGlobalCommonLibs.sh
Changed script to be local by default.
=> MAT-1105 Fixed conversion issues that were broken.

mat-fhir-commons/src/main/java/gov/cms/mat/fhir/commons/objects/FhirResourceValidationError.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/mat/DraftMeasureXmlProcessor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/rest/StandAloneLibraryController.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/packaging/LibraryPackagerService.java
INFORMATION and WARNING are now ignored.
=> MAT-1105 Fixed fhir validation errors on library push. 

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/AntlCqlParser.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlToMatXml.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlVisitor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/rest/MatXmlController.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/ValidationOrchestrationService.java, mat-fhir-services/src/main/resources/application-local.yaml, mat-fhir-services/src/test/java/gov/cms/mat/cql/parsers/VersionTest.java, mat-fhir-services/src/test/java/gov/cms/mat/fhir/services/service/ValidationOrchestrationServiceTest.java
Added in error,severity support as well if needed for future use in CqlToMatXml.
=> MAT-1173 Added severe errors for lib name and version.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/validation/ValueSetVsacAsync.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/components/vsac/VsacClient.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/RequestResponseLoggingInterceptor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/RestTemplateConfig.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/VsacConfig.java, mat-fhir-services/src/main/resources/application-local.yaml, mat-rest-commons/src/main/java/gov/cms/mat/cql/dto/CqlConversionPayload.java
Fixed some issues with valuesets.
Added awesome michael request/response logging.
=> MAT-1135 Fixed some issues with application-local.yaml.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/MeasureTranslator.java, mat-fhir-services/src/test/java/gov/cms/mat/fhir/services/rest/support/FhirValidatorProcessorTest.java
http://build.fhir.org/ig/HL7/cqf-measures/profiles.html
=> MAT-1228 add profiles to measure and library

docker-env.sh, mat-fhir-services/src/main/resources/application-local.yaml
Updated codesystem spreadsheet to new clone.
=> Updated codesystem spreadsheet to new clone.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java
Either a path or a searchParam must be provided, but not both
=> Fixed the fix for Lib's dataRequirement

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/packaging/LibraryPackagerService.java
It wasn't going through all libs to generate valuesets and code systems only the measure lib again and again.
=> MAT-1346 Fixed bug in LibraryPackagerSevice. 

mat-fhir-commons/src/main/java/gov/cms/mat/fhir/commons/model/HumanReadableCodeModel.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/LibraryCqlVisitor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/service/packaging/LibraryPackagerService.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/creators/FhirCreator.java
- null was being prepended to depends-on for libraries.
- codesystem URIs were not being included.
- measure version was dyslexic (revision and middle part reversed).
- Added sorting to valuesets and codesystems for lib bundles.
=> MAT-1302 Fixed packaging bugs:

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/LibraryCqlVisitor.java, scripts/updateHapiGlobalCommonLibs.sh
- Fixed bug in code based dataRequirements generation.
=> MAT-1302: Fixed packaging bugs

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlUtils.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java
Changed lib to just have one profile. It won't allow more than one.
=> MAT-1556 Fixed included lib version check.

cql-elm-translation/src/main/java/gov/cms/mat/cql_elm_translation/config/logging/BufferedStreamFilter.java, cql-elm-translation/src/main/java/gov/cms/mat/cql_elm_translation/config/logging/InterceptorConfig.java, cql-elm-translation/src/main/java/gov/cms/mat/cql_elm_translation/config/logging/RequestHeaderInterceptor.java, mapping-services/src/main/java/gov/cms/mat/qdmqicore/mapping/config/logging/BufferedStreamFilter.java, mapping-services/src/main/java/gov/cms/mat/qdmqicore/mapping/config/logging/InterceptorConfig.java, mapping-services/src/main/java/gov/cms/mat/qdmqicore/mapping/config/logging/RequestHeaderInterceptor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/logging/BufferedStreamFilter.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/logging/InterceptorConfig.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/logging/RequestHeaderInterceptor.java
Bugfix: Fixed issue that was bombing out because of some logging changes.
=> Bugfix: Fixed issue that was bombing out because of some logging changes.

mat-rest-commons/src/main/java/gov/cms/mat/fhir/rest/dto/cql/CqlPayload.java
CqlPayload now has a All args and No args constructor to fix serialization issue in dev-sbx.
=> BUGFIX Fix strange CQL errors we are seeing in dev-sbx.

cql-elm-translation/src/main/java/gov/cms/mat/cql_elm_translation/config/logging/RequestHeaderInterceptor.java, mapping-services/src/main/java/gov/cms/mat/qdmqicore/mapping/config/logging/BufferedStreamFilter.java, mapping-services/src/main/java/gov/cms/mat/qdmqicore/mapping/config/logging/RequestHeaderInterceptor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/config/logging/RequestHeaderInterceptor.java
- Cleared MDC log headers on completion. 
- Added reader request buffering where it was missing.
=> MAT-1574 Some final logging changes. 

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlToMatXml.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/parser/CqlUtils.java
Updated validations recenty added in CqlToMatXml to support conversion with severe errors.
=> MAT-1687 Fixed conversion of standalones with severe errors.. 

mat-fhir-commons/src/main/java/gov/cms/mat/fhir/commons/model/HumanReadableArtifacts.java, mat-fhir-commons/src/main/java/gov/cms/mat/fhir/commons/model/HumanReadableTypeModel.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/LibraryCqlVisitor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java
e.g.         //   First([Encounter] E where E.class = 'inpatient' sort by period.start desc)
should be:
{
"type": "Encounter"
},
=> Added type datarequirements back in.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/repository/CqlLibraryRepository.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/rest/StandAloneLibraryController.java
=> BUGFIX Fixed issue where pushAllVersionedLibs would fail if the query  to get all versioned libs was above the default for result set size.

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/cql/LibraryCqlVisitor.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/LibraryTranslator.java
- MAT-2731 Use code when deduping Data Requirements
- MAT-2731 Pass the Retrieve type for DRC backed Data Requirements
=> [MAT-2731] Check DRCs when deduping Data Requirements

mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/translate/MeasureTranslator.java
[MAT-2791](https://jira.cms.gov/browse/MAT-2791)
=> Changed URL for measure type

docker-compose.yml, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/repository/CqlLibraryExportRepository.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/repository/MeasureDetailsReferenceRepository.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/repository/MeasureExportRepository.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/repository/MeasureXmlRepository.java, mat-fhir-services/src/main/java/gov/cms/mat/fhir/services/rest/DbFixController.java
- Tune queries by checking for relevant nulls
- Pass JVM args to Docker for mat-fhir-services
=> Query Tuning for dbfix endpoint
